### ISSUE TITLE
invoke() should call CacheLoader in the RI

### ISSUE THREAD

**Issue by christian-esken** [jsr107/RI#54]
invoke() should call the CacheLoader, as it we can read in the API-Docs for `invoke()` listed in the JSR107 1.0 Spec, page 87:

> Invokes an {@link EntryProcessor} against the {@link Entry} specified by the provided key. If an {@link Entry} does not exist for the specified key, an attempt is made to load it (if a loader is configured) or a surrogate  {@link Entry}, consisting of the key with a null value is used instead. 

The reference implementation RICache does not call the CacheLoader in invoke(), and instead only does it when EntryProcessorEntry.getValue() is called. This fulfills the TCK, but IMO does not comply to the Spec. I am also wondering whether the corresponding TCK check (see below)  is compliant with the Spec (maybe yes, maybe no).

---

Background:

I stumbled across that when verifying tCache against the TCK. It is very hard (near impossible) to fulfill the unit test `invokeAllReadThroughEnabledGetOnNonExistentEntry(org.jsr107.tck.expiry.CacheExpiryTest)`, if you call the CacheLoader in the invoke() as required.

If the only operation is a getValue() the result is:
- RI will load the value and use expiryPolicy.getExpiryForCreation()
- tCache has the value loaded in invoke, so the value is read and expiryPolicy.getExpiryForAccess() is called

`
invokeAllReadThroughEnabledGetOnNonExistentEntry(org.jsr107.tck.expiry.CacheExpiryTest)  Time elapsed: 0.888 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <0>
     but: was <5>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at org.jsr107.tck.expiry.CacheExpiryTest.invokeAllReadThroughEnabledGetOnNonExistentEntry(CacheExpiryTest.java:1208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

**Comment by cruftex** [comment]
Interesting. I think doing an initial load is the simplest implementation. cache2k delays the load until `getValue()`. This is more effective, in case a new value gets inserted. So I just learned that this is, not strictly Spec conforming.

Regarding your referred TCK test:

For invoke it is the net effect that matters. If the load is just done on behalf of the invoke, the value is already available to the entry processor, it's not another cache access.

So I think the TCK tests are okay. You just need to correct your implementation ;)

However, if the RI is doing something different then the SPEC says, we should investigate this further. I suppose for efficiency a majority of implementations will delay the load until `getValue()`. If so, the Spec should be made more permissive and allow both variants.

I am not in favor to change the RI according to the Spec, since the RI behavior makes sense.

**Comment by christian-esken** [comment]
> For invoke it is the net effect that matters.
I think you refer to p.85-87 that describe the "net effect". The "net effect" there applies to the EntryProcessor.process(), and not to Cache.invoke(). So if invoke() would load the data, this should not be considered as part of the compound action of the EntryProcessor.

Additionally, if invoke() loads the data like described in the spec, I thought that means that the value MUST be available in the Cache after the EntryProcessor finishes. **So a delayed execution is not allowed, as there is no guarantee that getValue() is ever called.**

The effect of loading is not really described. It could mean different things:
- Load and put in the Cache before calling the EntryProcessor
- Load and put in the Cache after calling the EntryProcessor
- Load during getValue and put in the Cache after calling the EntryProcessor

Opinions on that?
I will read a bit more in the Spec, to see whether I have missed a part.

**Comment by cruftex** [comment]
You point out very well, what is confusing here. If you take everything literally what the Spec says, you end up with these contradictions.

> So if invoke() would load the data, this should not be considered as part of the compound action of the EntryProcessor.

Look on the conceptional side. The invocation of the entry processor for one entry is meant to be an atomic operation. Since it is atomic, there cannot be an outside visible order of the operations carried out. Any triggered load by an invoke cannot put something in the cache, since in the entry processor `setValue()` might be called.

So we can rule out this option: 
> Load and put in the Cache before calling the EntryProcessor

I am unsure how detailed the existing TCK tests are with these corner cases. Probably its a good idea to add some more TCK tests and check the existing implementations.

**Comment by christian-esken** [comment]
Cruftex, thanks for going into this so detailed.

> The invocation of the entry processor for one entry is meant to be an atomic operation.

Agree. The  Spec says, all operations are atomic. Due to explicit mentioning of the CacheLoader I thought that it is an exception. I will now assume that the "atomic" concept is more important and change my code.


-----

Before closing this ticket, lets just briefly discuss what should be done. IMO it would be enough to clarify the API-Docs, e.g. remove advocating to load the value and to have an advanced explanation on effects. Especially EntryProcessor has left me with more questions than answers.

-----
Part 1: Cache.invoke() and invokeAll() (on p.88)

Suggestion: remove loading/loader from the text, as it is confusing and IMO can produce a different net effect, e.g.think about an EntryProcessor doing a single MutableEntry.remove():
- Direct loading: First CacheLoader, then remove () means: **removed**
- Delayed loading: Only remove() means: **not removed**

Changed API-Docs would be:
> Invokes an {@link EntryProcessor} against the {@link Entry} specified by the provided key. If an {@link Entry} does not exist for the specified key, a surrogate {@link Entry}, consisting of the key with a null value is used instead.

-----
Part 2: EntryProcessor (on p.85.)

EntryProcessor  properly describes mutation effects, but IMO there are major flaws in the rest of the description.

1. The description after any of the 3 examples at "This will have the following {@link Cache} effects" look identical (and wrong for the second and third example).

2. The examples state that one must count only a single get or put, while in the description it reads:
> <h3>Effect of {@link MutableEntry} operations</h3> 
> {@link javax.cache.Cache.Entry} access, via a call to  {@link javax.cache.Cache.Entry#getValue()}, will behave as if  {@link Cache#get(Object)} was called for the key. This includes updating  necessary statistics, consulting the configured {@link ExpiryPolicy} and loading from a configured {@link javax.cache.integration.CacheLoader}. 

For me this is contradicting. That last sentence means, you have to update statistics on **each** call to getValue() and consult the ExpiryPolicy.

I would change the statistical effects description:
> Statistical effects are that of other compound operation like getAndRemove()or getAndPut(). Both a get and put (or delete) may be counted, but never multiple of the same type.

I am not yet sure how this effect CacheLoader and ExpiryPolicy: May they also only be called one time?




Invokes an {@link EntryProcessor} against the {@link Entry} specified by the provided key. If an {@link Entry} does not exist for the specified key, a surrogate {@link Entry}, consisting of the key with a null value is used instead.
Any outside visible effects of the EntryProcessor must be applied after returning from the EntryProcessor, including attempts to load a value from a CacheLoader.

**Comment by vbekiaris** [comment]
In https://github.com/jsr107/jsr107spec/commit/72373a0729446474a178cd7473287cb8ebf47537 `MutableEntry.getValue()` javadoc was added that explicitly states:
```
   * If the cache is configured to use read-through, and this method
   * would return null because the entry is missing from the cache,
   * the Cache's {@link CacheLoader} is called in an attempt to load
   * the entry.
```

**Comment by christian-esken** [comment]
I am not sure whether that addition is a good idea
- It requires to actually look at the Cache ("because the entry is missing from the cache"), and possibly *each time* you call MutableEntry.getValue()
- It does not deal with creating surrogate values, required by Cache.invoke()
- The Cache.invoke() documentation has not been changed.which is IMO wrong, as it explicitly requires to load the value.
- In sum this  means that  invoke() must load, and also MutableEntry.getValue() must load *each time* it is called.


I think this ticket should be kept open until clarification is done:
 - Should _"an attempt is made to load it"_ be removed from invoke()? I see no alternative.
 - If it remains,  would love to see a comment that states that invoke/invokeAll itself never mutates the Cache by itself.

**Comment by brianoliver** [comment]
I agree there are a few challenges with the wording of the specification and the RI implementation.   Personally I'm less concerned about the RI implementation.  I'd rather ensure that the specification and TCK is correct and then resolve any issues with the RI, bearing in mind we want to avoid breaking compliance with all existing implementations of the specification.   We control the RI so it's easy to fix.  We don't control other implementations.

That said, I think we need to step back a bit and understand the intent of EntryProcessors.   Basically they are designed with two purposes in mind.

1). To allow custom CAS operations, thus avoiding the typical "lock, get, update, put, unlock" style of operation against a cache.

2). Following on from above, they are designed to allow high-performance, low-latency operations in a distributed cache, avoiding multiple network round trips.

Forgetting about the second part for now, the idea was that all actions occurring within an EntryProcessor (like get, put, remove) would be seen as occurring atomically from the perspective of the cache when an EntryProcessor successfully completes, not from the perspective of some "backend" that has been integrated using CacheReaders/Writers.

Thus calling MutableEntry.getValue() is equivalent to calling Cache.get(), MutableEntry.putValue() is equivalent to calling Cache.put() and MutableEntry.remove() is equivalent to calling Cache.remove().

When a CacheReader/Writer is involved there are obvious side-effects as we don't attempt or expect to guarantee external resource atomicity.   eg: We deliberately didn't specify whether calling MutableEntry.getValue() multiple times would in fact result in multiple calls to a CacheReader (if one is configured).  We didn't do this for put or remove either.   I suspect however that the TCK tests for this kind of thing which is probably wrong.  

Personally speaking I think it's reasonable to assume that calling getValue() in an EntryProcessor only calls the CacheReader once (as the TCK suggests?) because it's assumed (stated somewhere) that during the execution of an EntryProcessor against a key, no other mutation of the key/value by any other Cache method.

This means that no other get, put or remove etc method calls can cause a CacheReader/Writer to fetch or mutate a Cache entry, in which case it's probably safe to assume a Cache entry hasn't been changed by other cache methods, meaning reading / writing once is also safe.

Of course there's the obvious challenge of "what happens if the underlying store the CacheReader/Writer is using changes during the execution of an EntryProcessor" or more specifically, what happens if the back-end representation of the entry changes after MutableEntry.getValue() is called?   In this case I feel it's safe to fall back to saying that "this is a cache".   It's safe for the Cache to "cache" the last read value as part of the EntryProcessor.

If we say that it's not safe, and that every call to MutableEntry.getValue() in an EntryProcessor must call through to the configured CacheReader, then we've lost the benefit of the Cache.   Constant read-through would be a waste of time.

I'm guessing we really need to clarify the possible interactions with a CacheReader/Writer a bit (or lot) more here, baring in mind that the Cache is not and should not be attempting manage transactional updates between the Cache and back-end store.  That was never the intent or purpose of this.

Perhaps we need to extend or allow providers to customize this behavior?  We specify the "default" behavior, thus not breaking any existing implementations and allow for others to be defined?

Just a thought.

**Comment by christian-esken** [comment]
brianoliver, you say  that EntryProcessor exists to "allow custom CAS operations". I agree and think the EntryProcessor documentation should stress that. It should document what that means for all aspects of the Cache. Aspects are e.g. ExpiryPolicy, CacheLoader and Mutation. Mutation is already a bit described:

> mutations will not take effect until after the process() method has completed execution.

It should be extended IMO:
- Reading: Read from Cache is done once for the first get, including CacheLoader, ExpiryPolicy, Statistics
- Mutation: Mutate take effect after the  the process() method has completed, including CacheWriter, Listener, ExpiryPolicy, Statistics
- Statistics must always represent the net effect on the Cache before and after the process() method. This means, maximum 1 read, 1 write, 1 delete is counted.

-----
In parts of issues that I see with the EntryProcessor documentation is:
- It describes not only EntryProcessor, but also the _"Effect of MutableEntry operations"_ . The described effects are IMO plain incompatible with the idea of only applying the net effect: _"mutation,_ via a call to MutableEntry.setValue(Object), will behave as if Cache.put(Object, Object) was called"_
- Most behavior (CacheLoader, ExpiryPolicy, Statistics, ...) is  only described by 3 examples. Specification by example is bad, and even worse if the examples are wrong. At least example 2 is wrong as it describes 2 puts that never happened ("second put will cause ...")

**Comment by cruftex** [comment]
Its great to have some feedback and discussion about the maybe most confusing item in the JCache standard. However, at some point we need to get back to some actionable item we can do and should do within a maintenance release.

I'll try to sort things a little.

From @christian-esken: 
> Stuff that belongs in EntryProcessor is documented in Cache.invoke() instead, namely CacheLoader and Surrogate Value

That is the initial problem in the issue description. Giving this a second thought I came to the conclusion that the Spec is simply wrong here and needs to be corrected (a simple fix, hooray!).
I can read from his comments, that christian probably thinks the same.

Opened a spec issue: https://github.com/jsr107/jsr107spec/issues/380

From @christian-esken:
> It should be extended IMO:
> Reading: Read from Cache is done once for the first get, including CacheLoader, ExpiryPolicy, Statistics, Surrogate Value
> Mutation: Mutate take effect after the process() method has completed, including CacheWriter, Listener, ExpiryPolicy, Statistics
> Statistics must always represent the net effect on the Cache before and after the process() method. This means, maximum 1 read, 1 write, 1 delete is counted.

This is to brief to put into the Spec and every point needs some broad discussion to ensure that its not to strict. The first priority of the Spec isn't to tell the vendors how to implement a cache, but to tell how a cache needs to behave to be able to implement useful and consistent applications. There should be as much freedom for the vendor as possible. 

You shouldn't nail down whether the ExpiryPolicy is called on read or when the operation is finished. What about the sequence `entry.getValue(); throw new Exception();` Should the read be counted in the statistics, although the operation itself didn't complete successfully? Would the sequence `entry.getValue(); entry.setValue()` generate two or only one call to the expiry policy? It doesn't matter, you can create useful applications with leaving this an implementation specific behavior.

The effect on statistics, in general, is not specified in detail but tested very rigorously by the TCK. When we get more detailed here, all the other CAS-operations need to get an update as well. If we should do something here, we need an issue to add more detail about statistics in general.

From @brianoliver:
> If we say that it's not safe, and that every call to MutableEntry.getValue() in an EntryProcessor must call through to the configured CacheReader, then we've lost the benefit of the Cache. Constant read-through would be a waste of time.

Yes&No :)

Saying that the loader is invoked only once when the value is missing is consistent with the general idea of the cache and loader. But, OTOH, a cache is temporary storage and may forget its value at any time. So the spec shouldn't say and test that the loader is called only once, but one would usually expect that.

But Brians' argument was about intermediate changes and consistency with the backend data. My opinion: If there is a problem with intermediate changes, an application just shouldn't use the "transparent loading feature" of the cache at this point and call the loader itself as needed.

With the Spec issue open, the initial and most important problem is addressed. I think we can close here.

The other things are relevant as well, but I would rather like to see TCK tests of more details and corner cases. These tests can make it more obvious what the spec implies now. That's better then making Spec more verbose and redundant.

**Comment by vbekiaris** [comment]
Closing this issue as it is being tracked on spec https://github.com/jsr107/jsr107spec/issues/380
