### ISSUE TITLE
CacheManager Properties are not preserved

### ISSUE THREAD

**Issue by gregrluck** [jsr107/RI#55]
See https://github.com/jsr107/jsr107tck/issues/102

**Comment by jfialli** [comment]
The lack of a copy constructor for Properties is quite frustrating.  

Prior to this fix, the RI was just making all properties passed into getCacheManager default properties in the new Properties object.  Not great, but did not fail following proper assertion.

         assertEquals("goofy", manager.getProperties().getProperty("dummy.com"));

Regretfully, test is comparing the Properties object that contains a defaults properties table
and a set of explicitly set property and values.

The current RI fix loses default properties by just iterating over Properties keys with Properties.keyset().  Actually a step backwards from before.
See https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#stringPropertyNames()
which does include defaults.  Making a new Properties iterating over this will still
not equal the old Properties(). (Since all properties would be promoted to being non-default
in new Properties()).


Here is scenario that is not handled by RI.

        CachingProvider provider = Caching.getCachingProvider();
        Properties defaultProps = new Properties();
        defaultProps.setProperty("defaultProperty", "defaultValue")'
        Properties properties = new Properties(defaultProps);
        properties.put("dummy.com", "goofy");

        CacheManager mgr1 = provider.getCacheManager(provider.getDefaultURI(), provider.getDefaultClassLoader(), properties);
        CacheManager manager = provider.getCacheManager();
        assertEquals(mgr1, manager);

        // This assertion is questionable given that Properties has two sets of
       // properties   defaults and the ones explicitly added by setProperty.
      // Recommend removing this assertion from tck test.
        assertEquals(mgr1.getProperties(), manager.getProperties());
       
        // the next line is safest TCK assertion.  This assertion has always passed.
         assertEquals("goofy", manager.getProperties().getProperty("dummy.com"));

       // next 2 assertions will fail against current RI when there are default properties.
        assertEquals("defaultValue", manager.getProperties().getProperty("defaultProperty"));  
        assertEquals(properties, manager.getProperties()); 

Strongest recommendation is to stop using following assertion in TCK
since this is checking both defaults and explicit property values of a Property.

        assertEquals(properties, manager.getProperties());

**Comment by cruftex** [comment]
Closing, tracked by: https://github.com/jsr107/jsr107tck/issues/102
